### ISSUE TITLE
Access denied when root password is empty

### ISSUE THREAD

**Issue by mauricioabreu** [docker-library/percona#18]
First, thanks for this image. Good job on this! :+1: 
### My problem

I am trying to use Percona for local development of a Django project. To make it compatible with virtual machines (using Vagrant + Virtualbox, for example) I set the root password to be empty.

Django settings:

``` python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'my_db',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'db',
        'TEST_CHARSET': 'UTF8',
    },
}
```

My docker-compose.yml:

```
version: '2'
services:
  db:
    image: percona
    environment:
      MYSQL_DATABASE: my_db
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
```
### The error

django.db.utils.OperationalError: (1045, u"Access denied for user 'root'@'172.19.0.4' (using password: NO)")

It works when I set passwords though...
