### ISSUE TITLE
SQL dump file not imported during container creating

### ISSUE THREAD

**Issue by v-escobar** [docker-library/percona#28]
I want to import the database structure of my project when the container is being created but looks like it does nothing.

This is how I have the container set up:

``` yaml
login-data-mysql:
    image: percona/percona-server
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=users
      - MYSQL_USER=users
      - MYSQL_PASSWORD=******
    volumes:
      - ./login/docker/mysql:/docker-entrypoint-initdb.d:ro
```

Inside of **login/docker/mysql** there is a file called dump.sql but it never gets imported.

What am I doing wrong? Any help would be appreciated.
