### ISSUE TITLE
How to map mysql data folder which is on windows 10 (host) to the mysql container which is installed in docker

### ISSUE THREAD

**Issue by Avimobi** [docker-library/percona#53]
Actually i want to use my running mysql database's data folder which is host windows 10 machine  from the container which is installed inside the docker. pls help me out thanks .

**Comment by tianon** [comment]
I'd recommend reading through https://docs.docker.com/engine/admin/volumes/bind-mounts/ and https://rominirani.com/docker-on-windows-mounting-host-directories-d96f3f056a2c.

In the future, these sorts of questions/requests would be more appropriately posted to [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).

**Comment by yosifkit** [comment]
If you are using "docker-toolbox" with "boot2docker" then this comment would apply (and has a handy compose example): https://github.com/docker-library/percona/issues/42#issuecomment-297865389.

If you are using "Docker for Windows", then this comment will apply: https://github.com/docker-library/percona/issues/42#issuecomment-298109103. In summary, it will not work at all on certain versions of percona/mysql/mariadb if you are trying to share a volume from Windows to a container running inside the VM.

**Comment by adamdehaven** [comment]
@yosifkit Just curious, did this ever get resolved? I'm still having the same issue. I can post my `docker-compose.yml` file if that's helpful

**Comment by yosifkit** [comment]
In some cases, it works fine to share a folder for the database files from windows to a Percona container. See the links in my last comment to see what will work. It depends on if you are using "docker-toolbox" with "boot2docker" or "Docker for Windows". (there is also a minimal compose example on the first link)

**Comment by adamdehaven** [comment]
I've tried using Docker for Windows as well as Docker Toolbox. Here's there relevant part of my yml file:

```
version: '3'
services:
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: my-image-name
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/srv/app
    links:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_DATABASE: docker_db
      DB_USERNAME: appuser
      DB_PASSWORD: password
  mariadb:
    image: mariadb:10.3.4
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: docker_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - .docker/db:/var/lib/mysql
```

This **won't** create the link and store the files on the Windows machine from the VM when the database is created
