### ISSUE TITLE
Can't mount local volume, its give permission denied.

### ISSUE THREAD

**Issue by roger-russel** [docker-library/percona#75]
# The problem on docker-compose up:

```
database    | Initializing database
database    | mysqld: Can't create/write to file '/var/lib/mysql/is_writable' (Errcode: 13 - Permission denied)
database    | 2018-11-28T15:08:33.615511Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
database    | 2018-11-28T15:08:33.618209Z 0 [ERROR] --initialize specified but the data directory exists and is not writable. Aborting.
database    | 2018-11-28T15:08:33.618234Z 0 [ERROR] Aborting
database    | 
database exited with code 1
```

# My docker-compose.yml
```
version: '2'
services:
    database:
        image: percona 
        container_name: database
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            -  ./database:/var/lib/mysql
        ports:
            - "3306:3306"
```

# Docker version

```
$ docker -v
Docker version 18.09.0, build 4d60db4
```

```
$ docker-compose version
docker-compose version 1.23.1, build b02f1306
docker-py version: 3.5.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

# Selinux is disabled
```
$ sestatus
SELinux status:                 disabled
```

# Trivia

## Folder is created

It's create ./database folder like this;
`drwxr-xr-x   2 root  root     6 nov 28 13:04 database`

## Mysql official works

If instead of Percona I use Mysql its works fine.

```
version: '2'
services:
    database:
        image: mysql 
        container_name: database
        environment:
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            -  ./database:/var/lib/mysql
        ports:
            - "3306:3306"
```

## Poor solution

I make it works creating ./database with 777 permission in advance.
But I'd prefer that works like MySql official image.

## OS

```
cat /etc/os-release 
NAME=Fedora
VERSION="29 (Workstation Edition)"
ID=fedora
VERSION_ID=29
PLATFORM_ID="platform:f29"
PRETTY_NAME="Fedora 29 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:29"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f29/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=29
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=29
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

```
$ uname -r
4.19.4-300.fc29.x86_64

```
